export const formInitialState = {
  formSubmitted: false,
  formInvalid: true,
  accordiansState: 'Open all',
  panel1state: false,
  panel2state: false,
  panel3state: false,
  creditAccountNumber: '',
  creditAccountList:[],
  submissionCourtList: [],
  countriesList: [],
  caveatApplicableType: 'person',
  caveat: {
    additionalInformation: '',
    addressLineOne: '',
    addressLineTwo: '',
    addressLineThree: '',
    cityOrTown: '',
    companyRegistrationNumber: '',
    actingUnderLegalCapacity: false,
    actingUnderLegalCapacityCaveat: false,
    actingUnderLegalCapacityDetail: '',
    country: 'Scotland',
    email: '',
    fax: '',
    name: '',
    partyType: 2,
    isPartyLodger: true,
    phone: '',
    postcode: '',
    remarks: '',
    dateOfBirth: '',
    firstName: '',
    lastName: '',
    middleNames: '',
    sex: '',
    alias: '',
  },
  caveatorApplicableType: 'person',
  caveator: {
    additionalInformation: '',
    addressLineOne: '',
    addressLineThree: '',
    addressLineTwo: '',
    cityOrTown: '',
    companyRegistrationNumber: '',
    country: 'Scotland',
    email: '',
    fax: '',
    name: '',
    alias: '',
    actingUnderLegalCapacity: false,
    actingUnderLegalCapacityCaveator: false,
    actingUnderLegalCapacityDetail: '',
    dateOfBirth: '',
    firstName: '',
    lastName: '',
    middleNames: '',
    partyType: 1,
    phone: '',
    postcode: '',
    remarks: '',
    sex: ''
  },
  referenceNumber: '',
  renewalId: '',
  solicitorReferenceNumber: '',
  contactDetails: '',
  alternativeContactDetails: '',
  submissionCourtName: '',
  courtName: '',
  dateReceived: '',
  expiryDate: '',
  isApplicableToLodgingParty: false,
  isSealed: false,
  remarks: '',
  coveredActionTypesCos: {
    interimInterdict: true,
    interimOrders: true,
    interimOrdersOthers: true,
    windingUpOfCompanies: true,
    groupProceeding: true
  },
  coveredActionTypesSheriff: {
    interimInterdictInAnOrdinaryCause: true,
    interimOrdersInAnOrdinaryCause: true,
    interimOrdersInASummaryApplication: true,
    orderForIntimationOfPetitionToWindup: true,
    orderForAppointmentOfAnAdministrator: true
  },
  addressSearchResults: {
    data: []
  }
}